services:
  grainob-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grainob-db
    ports:
      - "3309:3306"
    networks:
      - grainob-network
    volumes:
      - ./database:/var/lib/mysql

  grainoperationapi:
    image: grainoperationapi-image
    build:
      context: ./backend/GrainOperationAPI/
    ports:
      - "5003:5003"
    depends_on:
      - grainob-mysql
    networks:
      - grainob-network

  grainob-frontend:
    image: grainob-frontend-image
    build: 
        context: ./frontend/grainob-frontend
        dockerfile: Dockerfile
    ports:
      - "8085:4200"
    volumes:
      - ./frontend/grainob-frontend:/app
      - /app/node_modules
    networks:
      - grainob-network

  grainob-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8185:80"  # Assuming phpMyAdmin is served on port 80 inside the container
    depends_on:
      - grainob-mysql
    environment:
      PMA_HOST: grainob-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - grainob-network

  python-simulation:
    build: ./Simulation
    depends_on:
      - grainob-mysql
      - grainoperationapi
      - grainob-frontend
    networks:
      - grainob-network

networks:
  grainob-network:
    driver: bridge
